package com.np.database.orm;



import com.np.database.orm.biz.DbTypeEnum;
import com.np.database.orm.session.DefaultSqlSession;

public class OrmDDLTest {


    public static void main(String[] args) {

        //1、发起执行
        NpDbConfig dbConfig = NpDbConfig.builder()
                .dbTypeEnum(DbTypeEnum.POSTGRESQL)
                .ip("127.0.0.1")
                .port(8432)
                .dbName("postgres")
                .user("postgres")
                .password("postgres")
                .build();

        NpDatasource npDatasource = new NpDatasource(dbConfig);

        DefaultSqlSession session = (DefaultSqlSession) npDatasource.getSession(true);

        try {


            session.executeDDL("CREATE TABLE author (\n" +
                    "id                INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),\n" +
                    "username          VARCHAR(255) NOT NULL,\n" +
                    "password          VARCHAR(255) NOT NULL,\n" +
                    "email             VARCHAR(255) NOT NULL,\n" +
                    "bio               TEXT,\n" +
                    "favourite_section VARCHAR(25),\n" +
                    "PRIMARY KEY (id)\n" +
                    ")");

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                session.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

}
